name: Foo bar

on:
  push:
  pull_request:
  schedule:
    - cron:  '* * * * *'

jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Context github
        run: |
          echo ${{ toJSON(github) }}
      - name: Context env
        run: |
          echo ${{ toJSON(env) }}
      - name: Context job
        run: |
          echo ${{ toJSON(job) }}
      - name: Context steps
        run: |
          echo ${{ toJSON(steps) }}
      - name: Context runner
        run: |
          echo ${{ toJSON(runner) }}
      - name: Context strategy
        run: |
          echo ${{ toJSON(strategy) }}
      - name: Context matrix
        run: |
          echo ${{ toJSON(matrix) }}
      - name: Context needs
        run: |
          echo ${{ toJSON(needs) }}
