name: Foo bar

on:
  push:
  pull_request:
  schedule:
    - cron:  '7 17 * * 3' # 17:07 UTC on Wednesday
  release:
    types: [published]

jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git config
        run: |
          git config user.name
          git config user.email
          git config --global user.name
          git config --global user.email

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/edjopato/website-stalker
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Context github
        continue-on-error: true
        run: ${{ toJSON(github) }}
      - name: Context env
        continue-on-error: true
        run: ${{ toJSON(env) }}
      - name: Context job
        continue-on-error: true
        run: ${{ toJSON(job) }}
      - name: Context steps
        continue-on-error: true
        run: ${{ toJSON(steps) }}
      - name: Context runner
        continue-on-error: true
        run: ${{ toJSON(runner) }}
      - name: Context strategy
        continue-on-error: true
        run: ${{ toJSON(strategy) }}
      - name: Context matrix
        continue-on-error: true
        run: ${{ toJSON(matrix) }}
      - name: Context needs
        continue-on-error: true
        run: ${{ toJSON(needs) }}
