on:
  push:
  pull_request:

jobs:
  github-release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Package (-nix)
        if: runner.os != 'Windows'
        run: >
          tar --gzip -cvf bla.tar.gz
          README.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bla
          path: >
            *.zip
            *.tar.gz

      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: >
            *.zip
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
